import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href="/">Home</Link>
          {" | "}
          <Link href="/users">Users</Link>
          {" | "}
          <Link href="/blogs">Blogs</Link>
          {" | "}
          <Link href="/blogs/new">Create New</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
